apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels: 
        app: client
    spec:
      containers:
        - name: client
          image: brandonshearin/client-prod
          env:
            - name: GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: google-id
                  key: GOOGLE_ID
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: GOOGLE_SECRET
            - name: TWITTER_ID
              valueFrom:
                secretKeyRef:
                  name: twitter-id
                  key: TWITTER_ID
            - name: TWITTER_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitter-secret
                  key: TWITTER_SECRET
            - name: TWITTER_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twitter-bearer-token
                  key: TWITTER_BEARER_TOKEN
            - name: EMAIL_SERVER_USER
              value: apikey
            - name: EMAIL_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-server-password
                  key: EMAIL_SERVER_PASSWORD
            - name: EMAIL_SERVER_HOST
              value: smtp.sendgrid.net
            - name: EMAIL_SERVER_PORT
              value: "587"
            - name: EMAIL_FROM
              value: bshearin15@gmail.com
            - name: NEXT_AUTH_URL
              value: https://www.squawktherapy.com
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: DATABASE_URL
            - name: NEXT_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: next-auth-secret
                  key: NEXT_AUTH_SECRET


---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000 # next listens to port 3000 by default so listen to that one