apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels: 
        app: client
    spec:
      containers:
        - name: client
          image: brandonshearin/client-prod
          env:
            # - name: BASE_URL
            #   value: "http://squawktherapy.com"
            # - name: HOST
            #   value: "www.squawktherapy.com"
            - name: CLIENT_SIDE_URL
              value: "https://www.squawktherapy.com"

---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000 # next listens to port 3000 by default so listen to that one