apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template: # the template says how to create each individual pod that the deployment will manage
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: brandonshearin/comments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: squawk
            - name: MONGO_KEY
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_KEY
            - name: DB_NAME
              value: comments-service
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service # default behavior, when no type is provided, is to create a ClusterIP service
metadata:
  name: comments-srv
spec:
  selector:
    app: comments
  ports:
    - name: comments
      protocol: TCP
      port: 3000
      targetPort: 3000