name: deploy-gateway

on: 
  push:
    branches: 
      - master
    paths:
      - 'gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd gateway && docker build -t brandonshearin/gateway .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push brandonshearin/gateway
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} 
      - run: doctl kubernetes cluster kubeconfig save squawk
      - run: kubectl rollout restart deployment gateway-depl